### ISSUE TITLE
Remove master branch runs in generate-glyphs-file.yml GitHub Action workflow

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#123]
https://github.com/googlefonts/googlesans/pull/105#issuecomment-760933300

This does not need to be run on pushes to the master branch.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/blob/64d179f0ac3ee1896d988a5f06315eb5036e3f46/.github/workflows/generate-glyphs-file.yml#L7

**Comment by madig** [comment]
Oh, right. I am somewhat mystified by GHA's inner workings. I want 

```
on:
  push:
    # Sequence of patterns matched against refs/heads 
    branches: 
      - master # Push events on master branch 
      - "build/**" # Push events to branches matching refs/heads/build/[ANYTHING] 
      - "build-*" # Push events to branches matching refs/heads/build-[ANYTHING] 
    paths:
      - 'source/GoogleSans/*.glyphs'
 ```

to mean "if branch matches AND there are .glyphs files" but it seems to be a logical or?
