### ISSUE TITLE
Using pypy3 to speed up the CI

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#298]
It is possible to use pypy3 on GitHub Actions (see https://github.com/fonttools/fonttools/blob/b77d520/.github/workflows/test.yml#L79-L91) and the final font binaries are bit-identical, but the speed gains vary (see caveats below).

| Target | CPython 3.8            | Pypy 3.7.4  |
| --------- | ------------------- | --------- |
| gs-static | 250s | 200s |
| gs-vf | 320s | 180s |

These numbers came about with the current library versions, which include booleanOperations (sloooow!) and ufo2ft and fonttools that don't have the latest optimizations. Source is `build-gurmukhi`. CPU is a Ryzen 5 3400G, run inside WSL2.

I will test again after we upgraded libraries and maybe optimized the build system somewhat (parallelization).

**Comment by chrissimpkins** [comment]
Binary identical (should be or pypy3 has problems)?  I like it

**Comment by madig** [comment]
Yes they are :)

**Comment by chrissimpkins** [comment]
Niko, let me know if you have the specifics about your local config to turn off C extensions for this speedup.  We can implement this anytime.

**Comment by chrissimpkins** [comment]
For future reference, here are the docs on available pypy3 versions in GHA runners: 

https://github.com/actions/setup-python#available-versions-of-pypy

**Comment by chrissimpkins** [comment]
Bumping actions/setup-python to v2.x in preparation for this testing https://github.com/googlefonts/googlesans/pull/363

https://github.com/actions/setup-python/releases/tag/v2.2.0

**Comment by chrissimpkins** [comment]
Approach that Just is using in the GS CJK builds:

---

Here is our pypy requirements file:

https://github.com/BlackFoundryCom/gs-cjk-rcjk/blob/master/Proofer/requirements-pypy.txt

The main thing is to avoid as many C extensions as possible. In the case of fonttools, lxml is an important one.

I pretty much started with

  pip install --no-deps fontmake

Then ran our job, and added only the real necessary dependencies, until there were no more ImportErrors :)

Also check our GHA workflow file:

https://github.com/BlackFoundryCom/gs-cjk-rcjk/blob/master/.github/workflows/build-fonts-and-proof.yml

The cu2qu thing is important, Cosimo explained how to do that.

I built a pypy wheel for pathops, as that’s not on PyPI, and building it takes so long it pretty much negates the advantage of using pypy if it’s part of the workflow :)

Also note the --no-deps option in the pip install line for requirements-pypy.txt

---

See https://github.com/googlefonts/googlesans/issues/298#issuecomment-888519242 for the requirements.txt file linked above

See https://github.com/googlefonts/googlesans/issues/298#issuecomment-888519753 for the GH Actions config file linked above

**Comment by chrissimpkins** [comment]
Copy of the requirements-pypy.txt file linked above

```txt
git+https://github.com/BlackFoundryCom/rcjk-tools.git
attrs
cffi
cu2qu
fontmake
fontMath
fonttools
fs
greenlet
pytz
readline
six
typing-extensions
ufo2ft
ufoLib2
https://github.com/justvanrossum/skia-pathops-pypy-wheels/releases/download/v0.1.0/skia_pathops-0.6.0.post2-pp37-pypy37_pp73-linux_x86_64.whl
```

**Comment by chrissimpkins** [comment]
Copy of the GH Actions workflow linked above:

```yml
name: Build test fonts and PDF proof

on:
  # push:
  #   branches: [ master ]
  schedule:
    - cron: '0 0 * * *'  # once a day
  workflow_dispatch:  # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PyPy 3.7
        uses: actions/setup-python@v2
        with:
          python-version: pypy-3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          CU2QU_WITH_CYTHON=0 pip install --no-binary=cu2qu cu2qu
          pip install --no-deps -r Proofer/requirements-pypy.txt

      - name: RCJK Lint
        run: |
          mkdir -p Proofer/reports
          rcjklint *.rcjk --custom-checks=Proofer/customLintChecks.py > Proofer/reports/rcjklint.txt

      - name: Build rotated glyphs and collect merge data
        run: |
          mkdir -p Proofer/tmp_fonts
          python Proofer/buildRotatedLatin.py gslatin/*.ufo --output-dir=Proofer/tmp_fonts/
          python Proofer/collectMergeData.py --missing-characters=Proofer/reports/missing_characters.txt

      - name: Build fonts
        run: |
          python Proofer/buildBigFonts.py --log-level=INFO --skip-subsetting
          python Proofer/buildBigFonts.py --log-level=INFO --do-opsz --skip-subsetting

      - name: Localize fonts
        run: |
          python Proofer/localizeFonts.py --locale=SC Proofer/tmp_fonts/GSCJK-*.?tf
          python Proofer/localizeFonts.py --ttc Proofer/tmp_fonts/GSCJK-*.?tf
          python Proofer/localizeFonts.py --locale=SC Proofer/tmp_fonts/GSCJKOpsz-*.?tf

      - name: Storing font artifacts
        uses: actions/upload-artifact@master
        with:
          name: fonts
          path: Proofer/fonts
          retention-days: 4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Proofer/requirements.txt

      - name: Make PDF proofs
        run: |
          python Proofer/makeProofs.py

      - name: Storing PDF proof artifacts
        uses: actions/upload-artifact@master
        with:
          name: proofs
          path: Proofer/proofs
          retention-days: 4

      - name: Make reports
        run: |
          curl -O https://raw.githubusercontent.com/BlackFoundryCom/HanGlyphComposition/master/DeepComponents/LocalizedCharacters2DeepComponents.txt
          python Proofer/localisation.py LocalizedCharacters2DeepComponents.txt
          curl -O https://raw.githubusercontent.com/BlackFoundryCom/HanGlyphComposition/master/GlyphsDeepComposition/DeepComponents2characters.txt
          python Proofer/progressData.py DeepComponents2characters.txt
          python Proofer/hangul_progressData.py

      - name: Storing report artifacts
        uses: actions/upload-artifact@master
        with:
          name: reports
          path: Proofer/reports
          retention-days: 4

      - name: Commit Evolution CSV
        uses: EndBug/add-and-commit@v6
        with:
          add: 'Proofer/*evolution*.csv'
```
