### ISSUE TITLE
Review Georgian calt positioning feature code

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#328]
Designer intent:

```fea

@punctuation_centered = [periodcentered bullet hyphenbullet hyphen softhyphen endash emdash horizontalbar plus minus multiply equal notequal greater less approxequal asciitilde logicalnot infinity];

@punctuation_all = [asterisk asterisk.num asterism backslash braceleft braceleft.cap braceright braceright.cap bracketleft bracketleft.cap bracketright bracketright.cap bullet bullet.cap colon colon.tf colon.time comma comma.tf doublequestion ellipsis emdash emdash.cap endash endash.cap exclam exclamationquestion exclamdouble exclamdown exclamdown.cap flowerpunctuationmark guillemetleft guillemetleft.cap guillemetright guillemetright.cap guilsinglleft guilsinglleft.cap guilsinglright guilsinglright.cap horizontalbar hyphen hyphen.cap hyphenbullet lowasterisk numbersign numbersign.cap numbersign.tf parenleft parenleft.cap parenright parenright.cap period period.tf periodcentered question questiondown questiondown.cap questionexclamation quotedbl quotedblbase quotedblleft quotedblright quoteleft quoteright quotesinglbase quotesingle semicolon semicolon.tf slash softhyphen twoasterisksvertical underscore paragraph-georgian paragraph-georgian.case colon.loclGEO semicolon.loclGEO];

@spaces_all = [emquad emspace enquad enspace figurespace fourperemspace hairspace punctuationspace sixperemspace space nbspace thinspace threeperemspace zerowidthspace space.tf];

    pos @geor_lowercase @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @spaces_all @punctuation_centered @punctuation_centered' <0 -25 0 0>;

    pos @geor_lowercase @punctuation_centered @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @punctuation_centered @punctuation_centered' <0 -25 0 0>;

    pos @punctuation_centered' @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_centered @geor_lowercase <0 -25 0 0>;


    pos @geor_lowercase @punctuation_all @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_all @geor_lowercase <0 -25 0 0>;

    pos @geor_lowercase @punctuation_all @punctuation_centered' <0 -25 0 0>;
    pos @punctuation_centered' @punctuation_all @geor_lowercase <0 -25 0 0>;

    pos @geor_lowercase @punctuation_all @punctuation_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @punctuation_all @punctuation_all @spaces_all @punctuation_centered' <0 -25 0 0>;

    pos @punctuation_centered' @punctuation_all @punctuation_all @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_all @punctuation_all @geor_lowercase <0 -25 0 0>;
```

Related thread where the conversation began #310

**Comment by chrissimpkins** [comment]
Associated toml for shaping tests around this feature code:

```toml
[meta]
build_commit = ""

[input.features]
calt = true

[input]
comparison_mode = "full"
text = [
    "abo- აბო-", # the dash and other marks located in punctuation.centered should be shifted down with 25 point more as same symbol next to the Latin character
    "abo· აბო·",
    "abo— აბო—",
    "abo+ აბო+",
    "abo - აბო -", # it should work when space is used between letters and marks
    "abo,- აბო,-", # it should work when other mark is used between letters and marks
]
```

Removed in https://github.com/googlefonts/googlesans/pull/310/commits/729f34897784fe6f087321360232c38faa1d7598
